### ISSUE TITLE
Crash on latest nightly

### ISSUE THREAD

**Issue by ErikNatanael** [mitchmindtree/nannou-rustgpu-raytracer#2]
Screenshots and concept looks awesome and I can't wait to try it. On the latest nightly on my machine, it crashes with the following error though, trying to compile the shader I'm guessing: 
```
     Running `target/release/nannou-raytracer-app`
   Compiling nannou-raytracer-shader v0.1.0 (/home/erik/git/nannou-rustgpu-raytracer/shader)
warning: unused import: `Vec3`
 --> shader/src/lib.rs:9:47
  |
9 | use spirv_std::glam::{vec2, vec3, vec4, Vec2, Vec3, Vec4};
  |                                               ^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: OpCopyMemorySized without OpCapability Addresses
    --> /home/erik/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:1861:14
     |
1861 |     unsafe { copy_nonoverlapping(src, dst, count) }
     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error; 1 warning emitted

error: could not compile `nannou-raytracer-shader`

To learn more, run the command again with --verbose.
thread 'main' panicked at 'Crate had no .spv artifacts', /home/erik/.cargo/git/checkouts/rust-gpu-8a6af324770bf590/a1e349b/crates/spirv-builder/src/lib.rs:465:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    26638 segmentation fault (core dumped)  cargo run --release -p nannou-raytracer-app
```
What nightly version are you using? I tried a couple of different ones from May, but those wouldn't compile at all.
I also needed to install llvm-tools-preview for compilation to work and I installed rust-src and rustc-dev as components, guessing those were what you meant in the readme.

**Comment by mitchmindtree** [comment]
Hey thanks for opening this @ErikNatanael! I'll do a commit for those required components now. Here's the nightly version I'm using (on NixOS):

```
[nix-shell:~]$ rustc --version
rustc 1.54.0-nightly (e4a603270 2021-06-07)

[nix-shell:~]$ cargo --version
cargo 1.54.0-nightly (0cecbd673 2021-06-01)
```

I wonder where that error is occurring... I'd be curious to see the full backtrace if possible? That error tends to popup when trying to derefence a slice or sometimes a reference to an array from memory, but i'd worked around all the errors that I ran into on my machine. I wonder if there's some difference between compilation behaviour on different targets?

**Comment by ErikNatanael** [comment]
Nice, it works with that exact nightly version. Very cool! Installation steps for posterity:
```
$ rustup default nightly-2021-06-08
$ rustup component add llvm-tools-preview 
$ rustup component add rustc-dev 
$ rustup component add rust-src
$ cargo run --release -p nannou-raytracer-app
```
Here is the full backtrace of the crash I had before, still the same with the latest nightly (rustc 1.55.0-nightly (539d7bd39 2021-06-14)): 
```
error: OpCopyMemorySized without OpCapability Addresses
    --> /home/erik/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:1861:14
     |
1861 |     unsafe { copy_nonoverlapping(src, dst, count) }
     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error; 1 warning emitted

error: could not compile `nannou-raytracer-shader`

To learn more, run the command again with --verbose.
thread 'main' panicked at 'Crate had no .spv artifacts', /home/erik/.cargo/git/checkouts/rust-gpu-8a6af324770bf590/a1e349b/crates/spirv-builder/src/lib.rs:465:37
stack backtrace:
   0:     0x7fb26342ef40 - std::backtrace_rs::backtrace::libunwind::trace::hfa838fc631229987
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7fb26342ef40 - std::backtrace_rs::backtrace::trace_unsynchronized::h93a23e36ec026219
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb26342ef40 - std::sys_common::backtrace::_print_fmt::hba56c7f796a4152f
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fb26342ef40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h214637f1e26310e1
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fb26349c94c - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/core/src/fmt/mod.rs:1110:17
   5:     0x7fb263420905 - std::io::Write::write_fmt::heb07fc0616bbd06d
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/io/mod.rs:1588:15
   6:     0x7fb263432dcb - std::sys_common::backtrace::_print::h2c2441c37e894fb5
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fb263432dcb - std::sys_common::backtrace::print::h4fb679ac439362ea
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fb263432dcb - std::panicking::default_hook::{{closure}}::h56bbadec2356e5d2
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/panicking.rs:208:50
   9:     0x7fb2634328a1 - std::panicking::default_hook::hb25822b45f6fdc4e
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/panicking.rs:225:9
  10:     0x7fb2634335d4 - std::panicking::rust_panic_with_hook::h4da5578e7277d2d4
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/panicking.rs:622:17
  11:     0x7fb2634330b7 - std::panicking::begin_panic_handler::{{closure}}::h003783ddb3cba4e8
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/panicking.rs:519:13
  12:     0x7fb26342f41c - std::sys_common::backtrace::__rust_end_short_backtrace::hd138d2032731ed21
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x7fb263433019 - rust_begin_unwind
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/panicking.rs:515:5
  14:     0x7fb2633fdf51 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/core/src/panicking.rs:92:14
  15:     0x7fb2633fde43 - core::option::expect_failed::h52daa91c8ef676fe
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/core/src/option.rs:1243:5
  16:     0x55fe9a25de68 - spirv_builder::SpirvBuilder::build::ha098c3eab60fa12f
  17:     0x55fe9a20afb4 - nannou_raytracer_app::model::h37a2569696564442
  18:     0x55fe9a1cfd88 - nannou::app::Builder<M,E>::run::h5814c45da0b1d16a
  19:     0x55fe9a20a714 - nannou_raytracer_app::main::h99f4e332ddfa51af
  20:     0x55fe9a1fcf33 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9269d3df36581cc8
  21:     0x55fe9a1fcf49 - std::rt::lang_start::{{closure}}::hc40226a41153c84a
  22:     0x7fb263433bd9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd933294140eb11aa
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/core/src/ops/function.rs:259:13
  23:     0x7fb263433bd9 - std::panicking::try::do_call::h8342fe3d9218b807
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/panicking.rs:401:40
  24:     0x7fb263433bd9 - std::panicking::try::hcbd73d6d0d58a8f0
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/panicking.rs:365:19
  25:     0x7fb263433bd9 - std::panic::catch_unwind::hde9cf73f810acfcc
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/panic.rs:434:14
  26:     0x7fb263433bd9 - std::rt::lang_start_internal::heb39e7ea6e5d6f6f
                               at /rustc/0a8629bff642c3c3b84bb644c0099194f063b627/library/std/src/rt.rs:34:21
  27:     0x55fe9a20c1b2 - main
  28:     0x7fb262fa80b3 - __libc_start_main
  29:     0x55fe9a1aa53e - _start
  30:                0x0 - <unknown>
[1]    12304 segmentation fault (core dumped)  cargo run --release -p nannou-raytracer-app
```

**Comment by mitchmindtree** [comment]
Good to hear it's working with that nightly version at least!

Ahh it's a pity that backtrace doesn't give us much more info about where exactly this code is in the shader, though it makes sense that it wouldn't in retrospect as it's the SpirvBuilder that's failing. I wonder if one of the rust core implementations that the code relies on was changed to use this?

```
1861 |     unsafe { copy_nonoverlapping(src, dst, count) }
```

Or maybe there's a crate specified in the `Cargo.lock` that is tied to the installed compiler version :thinking: Out of curiosity, if you update nightly and also run `cargo update` in the project root, does the result work? It would make sense that there might need to be some synchronisation between the installed compiler version and whatever crates are taking advantage of the `rustc-dev` rustup component.

**Comment by ErikNatanael** [comment]
Yeah very little info there. Good idea, but it unfortunately made no difference, neither did removing Cargo.lock and running cargo clean.

**Comment by interpol-kun** [comment]
Same error for me. Latest nightly `rustc 1.55.0-nightly (539d7bd39 2021-06-14)`, after `cargo update`.

**Comment by m0rphed** [comment]
Hey

I was trying to run this with `rustc 1.56.0-nightly (30a0a9b69 2021-08-17)` and
compilation failed with these errors 👉 [pastebin_log](https://pastebin.com/7bi1hhvr)

> 
> Or maybe there's a crate specified in the `Cargo.lock` that is tied to the installed compiler version 🤔 Out of curiosity, if you update nightly and also run `cargo update` in the project root, does the result work? It would make sense that there might need to be some synchronisation between the installed compiler version and whatever crates are taking advantage of the `rustc-dev` rustup component.

I am new to rust, but I would guess that this issue somewhat related to compatibility of new `rustc nightly` version and **codegen-crate-name-fix** branch of [rust-gpu fork](https://github.com/mitchmindtree/rust-gpu?branch=codegen-crate-name-fix#a1e349bb) used as dependency [here](https://github.com/mitchmindtree/nannou-rustgpu-raytracer/blob/55a1d896c88f00675f8bc83e6da87c8956f2df1b/shared/Cargo.toml#L12)

Could not investigate it further due to the lack of rust debuging exp. 😞
